language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

before_install:
  - sudo apt-get update
  - bash .travis/setup_lua.sh
  - bash .travis/install_rote.sh
  - bash .travis/install_rocks.sh
  - sudo apt-get install valgrind ncbi-blast+ libboost-dev
  - sudo pip install cpp-coveralls

script:
  - . SETPATH
  - export LD_PRELOAD=/lib/x86_64-linux-gnu/libpthread.so.0
  - busted -c
  - LOAD_LUACOV=-lluacov busted
  - luarocks make --local && lua -lnpge.cpp -e'os.exit()'
  - busted -c
  - LOAD_LUACOV=-lluacov busted
  - sed 's@:.*/npge/@:.//src/npge/@' -i luacov.stats.out
  - bash .travis/test_with_valgrind.sh
  - bash .travis/c_coverage.sh

after_success:
  - coveralls -b . --dump c.report.json
  - luacov-coveralls -j c.report.json -v
