language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit # latest stable version (2.0.3)
    - LUA=luajit2.0 # current head of 2.0 branch
    - LUA=luajit2.1 # current head of 2.1 branch

before_install:
  - sudo apt-get update
  - source .travis/setenv_lua.sh
  - bash .travis/setup_rote.sh
  - bash .travis/setup_rocks.sh
  - sudo apt-get install valgrind ncbi-blast+ libboost-dev
  - sudo pip install cpp-coveralls

install:
  - luarocks make --local CFLAGS="-O0 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

script:
  - if [[ "$LUA" != *"luajit"* ]]; then .travis/lua-globals.sh `find src -name '*.lua'`; fi
  - tar -cf /tmp/lua-src.tar.gz src/npge/*.lua src/npge/*/*.lua
  - rm src/npge/*.lua src/npge/*/*.lua
  - export LD_PRELOAD=/lib/x86_64-linux-gnu/libpthread.so.0
  - lua -lnpge.cpp -e'os.exit()'
  - busted -c
  - busted --sort -o .appveyor/busted-print.lua
  - LOAD_LUACOV=-lluacov busted --sort -o .appveyor/busted-print.lua
  - echo 'os.exit = function() end' > exitless-busted
  - echo 'require "busted.runner"({ batch = true })' >> exitless-busted
  - if [[ "$LUA" != *"luajit"* ]]; then valgrind --error-exitcode=1 --leak-check=full --gen-suppressions=all --suppressions=.travis/nsswitch_c_678.supp lua exitless-busted; fi
  - sed 's@:.*/npge/@:.//src/npge/@' -i luacov.stats.out
  - luacov
  - tar -xf /tmp/lua-src.tar.gz

after_success:
  - coveralls -b . --dump c.report.json
  - luacov-coveralls -j c.report.json -v
